server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image_earch?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true



aliyun:
  oos:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tAM46qVRTQto1K732en
    accessKeySecret: U0cku5GE1cmyVnTcYWfXb3WKcJwr8c
    bucketName: imageearch
    filedir: image/
